### ISSUE TITLE
[Updater] yet another component to rewrite

### ISSUE THREAD

**Issue by cyyynthia** [powercord-org/powercord#230]
As many issues state, the updater will get a fairly large rewrite soon:tm: to add more functionality to it and make it better:tm: That issue will be used as a summary of all other issues, so we can track everything in here instead of having a lot of small issues.

 - [x] Auto-update plugin & themes as well (Original issue: #186)
Those should be updated as well and use the built-in hot-reload feature to prevent reloading the client for those updates
 - [x] More information about updates (Original issues: #162 #120)
As we're in beta we release a lot of updates and we'll maybe continue using just master branch when we're out of beta, idk. Anyway, a summary of the update like the list of commits included in that update would be nice. We can maybe make the toast be more simple at first, with like just two buttons ("Update & Restart", "More details...") and the last button would open the settings UI with a windows-like update screen with the list of updates and all actions possible.
 - [x] Changelogs (Original issues: #111)
When we release big updates or we consider there is enough content to make one, we could push Discord-like changelogs with what's new, API changes, etc... That'd be useful for people who don't want to read all commits to get an idea of what changed
 - [x] More update modes
We can add more modes to how the updater will react to new updates, like for example tell it to always download them, and then ask before reloading plugins, or only before reloading Discord, or do everything in background. We can also consider adding better ignore modes, for like ignoring commits or ignoring untill next reload in case Canary is dumb.

If you want to see more features in the updater, you can post them and i'll maybe include them in that list

**Comment by cloudrac3r** [comment]
> Auto-update plugin

Most of this be based off my plugin updater plugin, right?

> & themes

Presumably this would only work for themes that are cloned repos?

> More update modes

It would be useful to have options for "skip this commit" if something's broken upstream, or a "ignore updates until next client reload" if canary is broken and you are deliberately avoiding updating for as long as possible.

**Comment by cyyynthia** [comment]
> Most of this be based off my plugin updater plugin, right?

well yes but made in a good way so not really :^)

For themes they'll get the same UI as plugins so yeah only for git cloned themes, and I updated the last section to append those modes to the updater.

**Comment by cyyynthia** [comment]
![progress](https://owo.learndesk.app/d53ebd54aa.png)
![progress](https://owo.learndesk.app/4fd3e0266c.png)
![progress](https://owo.learndesk.app/44dcb6541c.png)

**Comment by davidcralph** [comment]
that's hot

**Comment by cloudrac3r** [comment]
that's hot

**Comment by cyyynthia** [comment]
https://i.bowser65.xyz/4aeb649751.mp4

**Comment by davidcralph** [comment]
DMCA

**Comment by cyyynthia** [comment]
no u
